/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
/**
 *
 * @author verin
 */
public class interfazATM extends javax.swing.JFrame {
public double saldo = 5000;
    /**
     * Creates new form interfazATM
     */
    public interfazATM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonConsultarSaldo = new javax.swing.JButton();
        jButtonDeposito = new javax.swing.JButton();
        jButtonRetiros = new javax.swing.JButton();
        jButtonHistorial = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel1.setText("                    Cajero ATM");

        jButtonConsultarSaldo.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jButtonConsultarSaldo.setText("Consultar Saldo");
        jButtonConsultarSaldo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonConsultarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarSaldoActionPerformed(evt);
            }
        });

        jButtonDeposito.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jButtonDeposito.setText("Deposito");
        jButtonDeposito.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDepositoActionPerformed(evt);
            }
        });

        jButtonRetiros.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jButtonRetiros.setText("Retiros");
        jButtonRetiros.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonRetiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetirosActionPerformed(evt);
            }
        });

        jButtonHistorial.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jButtonHistorial.setText("Historial");
        jButtonHistorial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonSalir.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonConsultarSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(jButtonDeposito, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(jButtonRetiros, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(jButtonHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(jButtonConsultarSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDeposito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRetiros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonHistorial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalir)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarSaldoActionPerformed
        JOptionPane.showMessageDialog(null,"Su saldo es de: " + saldo);
    }//GEN-LAST:event_jButtonConsultarSaldoActionPerformed

    private void jButtonDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDepositoActionPerformed
        String d = JOptionPane.showInputDialog(this,"¿Cuanto desea depositar a su cuenta?");
        if (d != null && !d.isEmpty()){
        
            try {
            double monto = Double.parseDouble(d);
            saldo += monto;
            JOptionPane.showMessageDialog(this, "Deposito agregado con exito " + saldo);
        } 
            catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Monto invalido" + e);
        
        
        }
        
        
        
        
        
        
        }
    }//GEN-LAST:event_jButtonDepositoActionPerformed

    private void jButtonRetirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetirosActionPerformed
        String z = JOptionPane.showInputDialog(this,"¿Cuanto desea retirar de su cuenta?");
        if (z != null && !z.isEmpty()){
        
            try {
            double monto = Double.parseDouble(z);
            
            if (monto <= saldo){
  
                saldo -= monto;
                JOptionPane.showMessageDialog(this,"Se ha retirado efetivo " + saldo);
            
            }else{
            JOptionPane.showMessageDialog(this,"Saldo insuficiente " + saldo);
            }
        } 
            catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Monto invalido" + e);
        
        
        }
        
        
        
        
        
        
        }
    }//GEN-LAST:event_jButtonRetirosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       interfazATM x = new interfazATM();
       x.setVisible(true);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazATM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultarSaldo;
    private javax.swing.JButton jButtonDeposito;
    private javax.swing.JButton jButtonHistorial;
    private javax.swing.JButton jButtonRetiros;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
